version: "2"
services:
  processor:
    build:
      context: https://github.com/Coinversable/validana-processor.git#v1.0.1
      dockerfile: Processor.Dockerfile
      args:
        NODEVERSION: 10
    restart: unless-stopped
    environment:
      VPROC_PRIVATEKEY: 
      # Should be the same as database PROCESSORPASS below.
      VPROC_DBPASSWORD: 
      # Should be the same as SIGNPREFIX below.
      VPROC_SIGNPREFIX: 
      VPROC_DBHOST: database
  node:
    build:
      context: https://github.com/Coinversable/validana-node.git#v1.0.1
      dockerfile: Node.Dockerfile
      args:
        NODEVERSION: 10
    restart: unless-stopped
    environment:
      VNODE_ISPROCESSOR: 'true'
      VNODE_ENCRYPTIONKEY: 
      # Make sure it is the same as the port you expose.
      VNODE_PROCESSORPORT: 56789
      VNODE_TLS: 'false'
      VNODE_KEYPATH: ''
      VNODE_CERTPATH: ''
      # Make sure it is the same as prefix above.
      VNODE_SIGNPREFIX: 
      # Make sure it is the same as the port you expose.
      VNODE_LISTENPORT: 29473
      # Should be the same as database BACKENDPASS below.
      VNODE_DBPASSWORD: 
      VNODE_DBHOST: database
      VNODE_DBUSER: backend
      VNODE_DBNAME: blockchain
    ports:
      - "29473:29473"
      - "56789:56789"
  database:
    build: 
      context: https://github.com/Coinversable/validana-processor.git#v1.0.1
      dockerfile: DB.Dockerfile
      args:
        PROCESSORPASS: 
        BACKENDPASS: 
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 
    volumes:
      - blockchain:/var/lib/postgresql/data
    expose:
      - "5432"
  server:
    build: 
      context: https://github.com/Coinversable/validana-server.git#v1.0.1
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VSERVER_DBPASSWORD: 
      VSERVER_DBHOST: database
      # Make sure it is the same as the port you expose.
      VSERVER_RESTPORT: 80
      # Make sure it is the same as the port you expose.
      VSERVER_WSPORT: 8080
      VSERVER_API: '{"v1": "/usr/node/dist/basics/basichandler.js"}'
      VSERVER_TLS: 'false'
      VSERVER_KEYPATH: ''
      VSERVER_CERTPATH: ''
    ports:
      - "80:80"
      - "8080:8080"

volumes:
  blockchain: